### ISSUE TITLE
Create a Dark Mode Option in the UI

### ISSUE THREAD

**Issue by karan0623** [karan0623/EventLink#23]

**Comment by cordasmd** [comment]
Myself and Ben worked to implement a dark mode option on our web app to improve the user experience. This was a suggestion that was presented to us from our initial survey that we did on the layout of our web application. There were a few bumps throughout this process, but we were able to figure out a couple elements such as the body and the cards. The nav bar element still needs to get corrected, but it is going in the right direction.

**Comment by cordasmd** [comment]
I've been working through blockers within this dark mode toggle over the past sprint. I figured out the elements and right now the dark mode toggle is fully working properly. Next steps will be to merge to master and then work through the conflicts in code that come up.

**Comment by cordasmd** [comment]
Successfully merged branch to master branch with Karan's help. Overall I created a new dark mode css page, created a dark mode script and created a dark mode toggle button to get the dark mode toggle to function within our web application.
